###############################################################################
# © Copyright IBM Corporation 2020
# Usage:
#  ansible-playbook -i <inventory> <playbook>
#
# Example:
#  ansible-playbook -i inventory submit_query_output_by_id.yaml
###############################################################################

---
- hosts: all
  collections:
    - ibm.ibm_zos_core
  gather_facts: no
  environment: "{{ environment_vars }}"

  tasks:
    - name: Submit JCL in a PDSE member
      zos_job_submit:
        src: TOMMY.JCL.CNTL(NADA)
        location: DATA_SET
      register: response
 
    - name: get response
      debug:
        msg: "{{ response }}"